/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;

import alertas.principal.AWTUtilities;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import categorias.categoria;

import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;


/**
 *
 * @author Rojeru San
 */
public class ModalUsuario extends javax.swing.JDialog {

    Timer timer = null;
    TimerTask task;
    int i = 32;

    public static int idMunicipio = 0;
    /**
     * Creates new form ModalProducto
     */
    public ModalUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);
        this.id.setVisible(false);
        Ubicar(0);
        this.nit.requestFocus();
       // this.nit.setEnabled(false);
        llenarMunicipio();
    }

    private void limpiarCampos() {

        this.nit.requestFocus();

        this.nit.setText("");
        this.nombre.setText("");

        Opciones.listar("");
    }
    
    //******************* LLENAR MUNICIPIO 
    
    
    private int  seleccionMunicipio(){
        
        municipios.Listar mun = (municipios.Listar) tipoE.getSelectedItem();
        return mun.getIdMunicipio();        
    }
    

    private void llenarMunicipio(){
        
        ArrayList<municipios.Listar> list = municipios.Opciones.obtener();
        
        DefaultComboBoxModel value = new DefaultComboBoxModel();
        tipoE.setModel(value);
        
        value.addElement(new municipios.Listar(0,"Ingresar Municipio"));
        
        for(municipios.Listar item : list){
            value.addElement(new municipios.Listar(item.getIdMunicipio(),item.getNombre()));
        } 
        
        
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        titulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        limpiar = new principal.MaterialButton();
        registrar = new principal.MaterialButton();
        id = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nit = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre1 = new app.bolivia.swing.JCTextField();
        direccion = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigo2 = new app.bolivia.swing.JCTextField();
        telefono = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        zona = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        latitud = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        longitud = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tipoE = new componentes.org1.bolivia.combo.SComboBox();
        email = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        password = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        zona1 = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alertas/img/fondo.png"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TITULO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 720, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        limpiar.setBackground(new java.awt.Color(255, 255, 255));
        limpiar.setForeground(new java.awt.Color(58, 159, 171));
        limpiar.setText("LIMPIAR CAMPOS");
        limpiar.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Limpiar campos</h4> </body> </html>");
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 160, 50));

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setForeground(new java.awt.Color(58, 159, 171));
        registrar.setText("REGISTRAR");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrarKeyTyped(evt);
            }
        });
        jPanel3.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 50));

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, -1));

        panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 720, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder1);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nit.setBorder(null);
        nit.setForeground(new java.awt.Color(58, 159, 171));
        nit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nit.setPlaceholder("APELLIDO");
        nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nitKeyTyped(evt);
            }
        });
        jPanel4.add(nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 240, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nombre.setBorder(null);
        nombre.setForeground(new java.awt.Color(58, 159, 171));
        nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre.setPlaceholder("NOMBRE");
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel4.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 230, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        nombre1.setBorder(null);
        nombre1.setForeground(new java.awt.Color(58, 159, 171));
        nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre1.setPlaceholder("NOMBRE");
        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre1KeyTyped(evt);
            }
        });
        jPanel4.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 240, 30));

        direccion.setBorder(null);
        direccion.setForeground(new java.awt.Color(58, 159, 171));
        direccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        direccion.setPlaceholder("DIRECCION");
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionKeyTyped(evt);
            }
        });
        jPanel4.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 240, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        codigo2.setBorder(null);
        codigo2.setForeground(new java.awt.Color(58, 159, 171));
        codigo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo2.setPlaceholder("CODIGO");
        codigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo2KeyTyped(evt);
            }
        });
        jPanel4.add(codigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 30));

        telefono.setBorder(null);
        telefono.setForeground(new java.awt.Color(58, 159, 171));
        telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefono.setPlaceholder("TELEFONO");
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel4.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        zona.setBorder(null);
        zona.setForeground(new java.awt.Color(58, 159, 171));
        zona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zona.setPlaceholder("ZONA");
        zona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zonaKeyTyped(evt);
            }
        });
        jPanel4.add(zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        latitud.setBorder(null);
        latitud.setForeground(new java.awt.Color(58, 159, 171));
        latitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        latitud.setPlaceholder("LATITUD");
        latitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                latitudKeyTyped(evt);
            }
        });
        jPanel4.add(latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 240, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        longitud.setBorder(null);
        longitud.setForeground(new java.awt.Color(58, 159, 171));
        longitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        longitud.setPlaceholder("LONGITUD");
        longitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                longitudKeyTyped(evt);
            }
        });
        jPanel4.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 240, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios/icono-usuario.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, 60));

        tipoE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUARIO", "ADMINISTRADOR", "NORMAL" }));
        tipoE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(tipoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 230, 30));

        email.setBorder(null);
        email.setForeground(new java.awt.Color(58, 159, 171));
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setPlaceholder("EMAIL");
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 240, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        password.setBorder(null);
        password.setForeground(new java.awt.Color(58, 159, 171));
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setPlaceholder("PASSWORD");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel4.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 240, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        zona1.setBorder(null);
        zona1.setForeground(new java.awt.Color(58, 159, 171));
        zona1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zona1.setName("dpi"); // NOI18N
        zona1.setPlaceholder("DPI");
        zona1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zona1KeyTyped(evt);
            }
        });
        jPanel4.add(zona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 240, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos/campo-nombre.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 680, 350));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 0) {
                    Cerrar();
                } else {
                    Ubicar(i);
                    i -= 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_cerrarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        if (this.nombre.getText().equals("") || this.nit.getText().equals("")|| this.direccion.getText().equals("") 
                || this.telefono.getText().equals("")|| this.zona.getText().equals("")|| this.latitud.getText().equals("")
                || this.longitud.getText().equals("")|| this.password.getText().equals("")|| this.email.getText().equals("")) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);
        }
        else {

            if (this.registrar.getText().equals("GUARDAR")) {

                usuarios.Sentencias s = new usuarios.Sentencias();

                s.setZona(Integer.parseInt(this.zona.getText()));
                s.setLatitud(Double.parseDouble(this.latitud.getText()));
                s.setLongitud(Double.parseDouble(this.longitud.getText()));
                s.setNombre(this.nombre.getText());
                s.setApellido(this.nit.getText());
                s.setDireccion(this.direccion.getText());
                s.setTelefono(this.telefono.getText());
                s.setEmail(this.email.getText());
                s.setPassword(this.password.getText());
                s.setDpi(this.zona1.getText());
                
                int seleccion =  seleccionMunicipio();
                System.out.println("esta es la seleccin de "+seleccion);
                if(seleccion == 0){
                    s.setIdmunicipio(idMunicipio);
                    System.out.println(idMunicipio);
                }else {
                    s.setIdmunicipio(seleccion);
                }
                
            
                int opcion = usuarios.Opciones.actualizar(s);
                if (opcion != 0) {
                    String fila = this.id.getText();
                    usuarios.Opciones.listar("");
                    SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                    sa.titulo.setText("¡HECHO!");
                    sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                    sa.msj1.setText("");
                    sa.setVisible(true);
                }

            } else {

                usuarios.Sentencias s = new usuarios.Sentencias();

                s.setZona(Integer.parseInt(this.zona.getText()));
                s.setLatitud(Double.parseDouble(this.latitud.getText()));
                s.setLongitud(Double.parseDouble(this.longitud.getText()));
                s.setNombre(this.nombre.getText());
                s.setApellido(this.nit.getText());
                s.setDireccion(this.direccion.getText());
                s.setTelefono(this.telefono.getText());
                s.setEmail(this.email.getText());
                s.setPassword(this.password.getText());
                s.setDpi(this.zona1.getText());
                
                int seleccion =  seleccionMunicipio();
                System.out.println("esta es la seleccin de "+seleccion);
                if(seleccion == 0){
                    s.setIdmunicipio(idMunicipio);
                    System.out.println(idMunicipio);
                }else {
                    s.setIdmunicipio(seleccion);
                }
                
            
                int opcion = usuarios.Opciones.registrar(s);
                if (opcion != 0) {
                    String fila = this.id.getText();
                    usuarios.Opciones.listar("");
                    SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                    sa.titulo.setText("¡HECHO!");
                    sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                    sa.msj1.setText("");
                    sa.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 352) {
                    timer.cancel();
                } else {
                    Ubicar(i);
                    i += 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_formWindowOpened

    private void registrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrarKeyTyped
       
    }//GEN-LAST:event_registrarKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
       
    }//GEN-LAST:event_nombreKeyTyped

    private void nitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitKeyTyped
      
    }//GEN-LAST:event_nitKeyTyped

    private void nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1KeyTyped

    private void direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionKeyTyped

    private void codigo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo2KeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoKeyTyped

    private void zonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zonaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_zonaKeyTyped

    private void latitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_latitudKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudKeyTyped

    private void longitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longitudKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyTyped

    private void zona1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zona1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_zona1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalUsuario dialog = new ModalUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton cerrar;
    public static app.bolivia.swing.JCTextField codigo2;
    public static app.bolivia.swing.JCTextField direccion;
    public static app.bolivia.swing.JCTextField email;
    public static javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static app.bolivia.swing.JCTextField latitud;
    private principal.MaterialButton limpiar;
    public static app.bolivia.swing.JCTextField longitud;
    public static app.bolivia.swing.JCTextField nit;
    public static app.bolivia.swing.JCTextField nombre;
    public static app.bolivia.swing.JCTextField nombre1;
    private org.edisoncor.gui.panel.Panel panel1;
    public static app.bolivia.swing.JCTextField password;
    public static principal.MaterialButton registrar;
    public static app.bolivia.swing.JCTextField telefono;
    public static componentes.org1.bolivia.combo.SComboBox tipoE;
    public static javax.swing.JLabel titulo;
    public static app.bolivia.swing.JCTextField zona;
    public static app.bolivia.swing.JCTextField zona1;
    // End of variables declaration//GEN-END:variables

    private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void Ubicar(int y) {
        this.setLocation(603, y - 200);
    }
}
